/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppMessages: typeof import('./components/app/AppMessages.vue')['default']
    ChangePwdDialog: typeof import('./components/user/ChangePwdDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LinkList: typeof import('./components/LinkList/LinkList.vue')['default']
    LinkListNode: typeof import('./components/LinkList/LinkListNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
