/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...page]': RouteRecordInfo<'/[...page]', '/:page(.*)', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/confirm': RouteRecordInfo<'/user/confirm', '/user/confirm', Record<never, never>, Record<never, never>>,
    '/user/login': RouteRecordInfo<'/user/login', '/user/login', Record<never, never>, Record<never, never>>,
    '/user/register': RouteRecordInfo<'/user/register', '/user/register', Record<never, never>, Record<never, never>>,
    '/user/restore-pwd': RouteRecordInfo<'/user/restore-pwd', '/user/restore-pwd', Record<never, never>, Record<never, never>>,
    '/user/verify-email': RouteRecordInfo<'/user/verify-email', '/user/verify-email', Record<never, never>, Record<never, never>>,
  }
}
